# Generated by Django 3.1.3 on 2020-11-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('cbfv', models.SmallIntegerField(choices=[(0, 'atom2vec'), (1, 'jarvis'), (2, 'jarvis_shuffled'), (3, 'magpie'), (4, 'mat2vec'), (5, 'mat_shuffled'), (6, 'oliynyk'), (7, 'random_200')], default=1)),
                ('mat_prop', models.SmallIntegerField(choices=[(0, 'Egap'), (1, 'ael_bulk_modulus_vrh'), (2, 'ael_debye_temperature'), (3, 'ael_shear_modulus_vrh'), (4, 'agl_log10_termal_expansion_300K'), (5, 'agl_thermal_conductivity_300K'), (6, 'energy_atom')], default=1, verbose_name='material property')),
                ('batch_size', models.IntegerField(default=64)),
                ('epochs', models.IntegerField(default=200)),
                ('learning_graph', models.ImageField(null=True, upload_to='graphs')),
                ('MAE', models.FloatField(default=None, null=True)),
                ('MSE', models.FloatField(default=None, null=True)),
                ('R2', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimizer', models.SmallIntegerField(default=1)),
                ('loss', models.SmallIntegerField(default=1)),
                ('learning_rate', models.FloatField(default=0.01)),
                ('regularization', models.SmallIntegerField(default=1)),
                ('dropout', models.FloatField(default=0.4)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.model')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.SmallIntegerField(choices=[(0, 'mean_squared_error'), (1, 'root_mean_squared_error'), (2, 'mean_absolute_error'), (3, 'mean_absolute_percentage_error'), (4, 'mean_squared_logarithmic_error'), (5, 'cosine_similarity'), (6, 'logcosh')], default=1)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.model')),
            ],
        ),
    ]
